[locator]
## Home Page
Web Inputs Try it out = //*[@href='/inputs' and @type='button']
Test Login Page Try it out = //*[@href='/login' and @type='button']

## Web Inputs Page
Input Number = //*[@id='input-number']
Input Text = //*[@id='input-text']
Input Password = //*[@id='input-password']
Input Date = //*[@id='input-date']

## Test Login Page
Username = //*[@id='username']
Password = //*[@id='password']
Login = //*[@id='submit-login']

